import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Seminary✏️</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>QUIX</div>

                <Button sx={{ backgroundColor: 'red' }} variant="outlined">Outlined</Button>
                <h1>CST-461:Quiz Dashboard</h1>

                <div>
                    <div >
                        <p>How you gonna proceed with CST-461 project ?</p>
                        <form>
                            <input type="radio" name="question-1" value="option-1"/>Option 1<br/>
                            <input type="radio" name="question-21" value="option-2"/>Option 1<br/>
                            <input type="radio" name="question-31" value="option-3"/>Option 1<br/>
                            <input type="radio" name="question-41" value="option-4"/>Option 1<br/>
                        </form>
                    </div>
                    <div >
                        <p>Did you completed CST:461 project ? </p>
                        <form>
                            <input type="radio" name="question-2" value="option-1"/>Option 1<br/>
                            <input type="radio" name="question-12" value="option-2"/>Option 1<br/>
                            <input type="radio" name="question-22" value="option-3"/>Option 1<br/>
                            <input type="radio" name="question-32" value="option-4"/>Option 1<br/>
                        </form>
                    </div>
                </div>

            </main>
        </>
    )
}
